### ISSUE TITLE
experience of msi gf63 thin?

### ISSUE THREAD

**Issue by sguptzz** [nmstreethran/notebook#11]
hey I saw your .linux directory and discovered that you use msi gf63 thin so what's the experience with it? also how does it work with xwayland/wayland if possible can you tell me?

**Comment by nmstreethran** [comment]
@sguptzz Works well in my experience. I use it primarily for scientific programming (with climate data) and GIS. I've tried a few games on Windows and they run pretty smoothly, but the device tends to get very hot. RAM definitely needs upgrading as it only comes with 8 GB installed.

**Comment by sguptzz** [comment]
> @sguptzz Works well in my experience. I use it primarily for scientific programming (with climate data) and GIS. I've tried a few games on Windows and they run pretty smoothly, but the device tends to get very hot. RAM definitely needs upgrading as it only comes with 8 GB installed. I don't have experience with wayland so can't comment on that.

oh thanks a lot for your time
